# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: doc/conf.py
  builder: dirhtml

python:
  version: 3.7
  system_packages: true
  
conda:
  environment: doc/environment.yml 