# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  version: "3.7"
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
  system_packages: true

sphinx:
    configuration: docs/conf.py